// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SmartCamera
{

public enum BoundingBox : byte
{
  NONE = 0,
  BoundingBox2d = 1,
};


}
